version: "3.5"
services:
  web:
    container_name: nanodefiner_web
    image: nanodefiner/nanodefiner:1.0.2
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    #volumes:
      #- "/path/to/config/dir/application.properties:/nanodefiner/config/application.properties"
      #- "/path/to/config/dir/hikari.properties:/nanodefiner/config/hikari.properties"
      #- "/path/to/config/dir/hibernate.properties:/nanodefiner/config/hibernate.properties"
      #- "/path/to/data/dir:/nanodefiner/data"
    networks:
      - nanodefiner
  db:
    container_name: nanodefiner_db
    image: mariadb:rc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nanodefiner_root
      MYSQL_USER: nanodefiner
      MYSQL_PASSWORD: nanodefiner
      MYSQL_DATABASE: nanodefiner
    #volumes:
      #- "/path/to/mysql/dir:/var/lib/mysql"
    networks:
      - nanodefiner
networks:
  nanodefiner:
    name: nanodefiner
